// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgyotYN-lL736B7bfwN-oT1sllELCXHUc',
    appId: '1:31888904508:web:19ded77359e8cbb0914e39',
    messagingSenderId: '31888904508',
    projectId: 'auth-bloc-1e31b',
    authDomain: 'auth-bloc-1e31b.firebaseapp.com',
    storageBucket: 'auth-bloc-1e31b.appspot.com',
    measurementId: 'G-2EM223QQV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EZIrmaFiM8gL2zkQgIAB85luZs0xSvU',
    appId: '1:31888904508:android:e24d801d4c847d01914e39',
    messagingSenderId: '31888904508',
    projectId: 'auth-bloc-1e31b',
    storageBucket: 'auth-bloc-1e31b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCt34fPHzXmxExOq5ddsAw1NvthmcI6-c',
    appId: '1:31888904508:ios:e55b6633c7f21a6e914e39',
    messagingSenderId: '31888904508',
    projectId: 'auth-bloc-1e31b',
    storageBucket: 'auth-bloc-1e31b.appspot.com',
    androidClientId: '31888904508-b266j41hfkfvuteph3cmokdmfushil9f.apps.googleusercontent.com',
    iosClientId: '31888904508-7l8qnn02onsige5huml38u4h98ngqb7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocDive2',
  );
}
